### ISSUE TITLE
Redundant file?

### ISSUE THREAD

**Issue by scottphc** [dhoerl/DHlibxls#25]
I cloned this repo and didn't modify anything, but it showed untracked files. Is it a redundant file?
![screen shot 2016-06-29 at 3 09 36 pm](https://cloud.githubusercontent.com/assets/1115510/16443514/e0089474-3e0b-11e6-8a0b-456d03a4955b.png)

I tried to see the file in Github, but it showed the error page. https://github.com/dhoerl/DHlibxls/tree/master/DHxlsReaderIOS.xcodeproj%A4xcuserdata/dhoerl.xcuserdatad/xcschemes

**Comment by dhoerl** [comment]
On 6/29/16 3:14 AM, Scott Chou wrote:
> I cloned this repo and didn't modify anything, but it showed untracked
> files. Is it redundant?
> screen shot 2016-06-29 at 3 09 36 pm
> <https://cloud.githubusercontent.com/assets/1115510/16443514/e0089474-3e0b-11e6-8a0b-456d03a4955b.png>
>
> I tried to see the file in Github, but it showed the error page.
> https://github.com/dhoerl/DHlibxls/tree/master/DHxlsReaderIOS.xcodeproj%A4xcuserdata/dhoerl.xcuserdatad/xcschemes
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhoerl/DHlibxls/issues/25>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAxml-kogvezmV4pb7LU3wkySkziZVzrks5qQhtTgaJpZM4JA1lJ>.
>

Its just a private scheme I used - probably the .gitignore was (or is) 
not excluding it. Don't worry about it.
