### ISSUE TITLE
Can't parse large .xls files when saved from Windows

### ISSUE THREAD

**Issue by jokeruger** [dhoerl/DHlibxls#27]
When trying to open large files (the 'dividing line' seems to be around 23,400 KB) that have been saved from Excel on Windows (the same file saved from Excel on OSX works fine), I get a crash on [DHxlsReader xlsReaderWithPath:]

* thread 24, stop reason = EXC_BAD_ACCESS (code=1, address=0x7fd35b0c35a4)
  * frame 0: 0x00000001104e6077 xls_dumpSummary(buf=<unavailable>, isSummary=0, pSI=0x000060800028f000) at xls.c:1395 [opt]
  * frame 1: 0x00000001104e5fa4 xls_summaryInfo(pWB=0x000060400011b1b0) at xls.c:1336 [opt]
  * frame 2: 0x00000001104fc476 -[DHxlsReader setWorkBook:](self=0x000060800027d9c0, _cmd=<unavailable>, wb=<unavailable>) at DHxlsReader.m:106 [opt]
  * frame 3: 0x00000001104fc342 +[DHxlsReader xlsReaderWithPath:](self=<unavailable>, _cmd=<unavailable>, filePath=<unavailable>) at DHxlsReader.m:75 [opt]

**Comment by dhoerlSA** [comment]
You didn't attach your file. Please provide the file and I can look at it.

**Comment by jokeruger** [comment]
Sorry for the delay. I have a spreadsheet that's demonstrating the issue but unfortunately it has some confidential data in it. So I've been removing that, but as I do I'm noticing the issue isn't directly tied to filesize. That was simply a coincidence of adding/removing columns in one specific tab of the spreadsheet, and that's the size it happened to be when those columns were modified. I'm doing some more investigation and will let you know if I learn anything else or get a copy of the spreadsheet I can share

**Comment by dhoerlSA** [comment]
Suggest you build with the latest SVN source (NOT the 1.4 release, the latest SVN trunk code). We fixed a few bugs in the past few months.

**Comment by jokeruger** [comment]
Thanks, I'll try that also

**Comment by jokeruger** [comment]
Was unable to get the latest code running properly (have run out of budget to look into this further), but we've avoided the issue by not calling for the workbook's summary
